apiVersion: v2
description: Devolift cronjob generic helm chart
name: generic-cron
version: 0.0.1
annotations:
  category: Cronjob
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
keywords:
  - devolift
  - generic
  - cronjob
icon: https://avatars.githubusercontent.com/u/18402183?s=200&v=4
sources:
  - https://github.com/Devolift/helm-charts/
home: https://devolift.com/
maintainers:
  - name: Matthieu Delmaire
    email: matthieu.delmaire@devolift.com
