image:
  # -- Docker image registry
  registry:
  # -- Docker repository
  repository: generic-service
  # -- Docker image tag
  tag: 0.0.1
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Docker registry secret names as an array
  pullSecrets: []

configmap:
  # -- Annotations added to the configmap resource
  annotations: {}
  # -- Labels added to the configmap resource
  labels: {}
  # -- Define data that will be into the configmap resource
  data: {}

cronjob:
  # -- Labels added to the cronjob resource
  labels: {}
  # -- Annotations added to the cronjob resource
  annotations: {}
  # -- Cronjob concurrency policy
  concurrencyPolicy: Allow
  # -- Cronjob schedule
  schedule: "*/2 * * * *"
  # -- Cronjob restart policy
  restartPolicy: OnFailure
  # -- Cronjob successfulJobsHistoryLimit
  successfulJobsHistoryLimit: 3
  # -- Cronjob failedJobsHistoryLimit
  failedJobsHistoryLimit: 1

# -- The name of the ServiceAccount to use (have to already exists)
serviceAccountName:

# -- Node labels for pod assignment
nodeSelector: {}

# -- Affinity for pod assignment
affinity: {}

# -- Tolerations for pods assignment
tolerations: []

# -- Use an alternate scheduler
schedulerName: null

securityContext:
  enabled: false
  runAsUser:
  runAsGroup:
  fsGroup:

# -- Topology Spread Constraints for pod assignment spread across your cluster
topologySpreadConstraints: {}

# -- Add additional init containers
initContainers: []

# -- Optionally specify extra list of additional volumeMounts
extraVolumeMounts: []

# -- Optionally specify extra list of additional volumes
extraVolumes: []

# -- Add additional sidecar containers
sidecars: []

# -- Override default container command
command: []

# -- Override default container args
args: []

# --  Array with extra environment variables to add in pods
extraEnvVars: []

# -- Optionally specify existing configMap which will be added to our pods
extraEnvVarsConfigMap: ""

# -- Optionally specify existing secret which will be added to our pods
extraEnvVarsSecret: ""

# -- Add extra annotations to the pods
podAnnotations: {}

# -- Add extra labels to the pods
podLabels: {}

livenessProbe:
  # -- Enable livenessProbe on containers
  enabled: false
  # -- Path for livenessProbe
  path: /health
  # -- Port for livenessProbe
  port: 80
  # -- Initial delay seconds for livenessProbe
  initialDelaySeconds: 300
  # -- Timeout seconds for livenessProbe
  timeoutSeconds: 3
  # -- Period seconds for livenessProbe
  periodSeconds: 10
  # -- Failure threshold for livenessProbe
  failureThreshold: 5
  # -- Success threshold for livenessProbe
  successThreshold: 1

readinessProbe:
  # -- Enable readinessProbe on containers
  enabled: false
  # -- Path for readinessProbe
  path: /health
  # -- Port for readinessProbe
  port: 80
  # -- Initial delay seconds for readinessProbe
  initialDelaySeconds: 300
  # -- Timeout seconds for readinessProbe
  timeoutSeconds: 2
  # -- Period seconds for readinessProbe
  periodSeconds: 5
  # -- Failure threshold for readinessProbe
  failureThreshold: 5
  # -- Success threshold for readinessProbe
  successThreshold: 1

startupProbe:
  # -- Enable startupProbe on containers
  enabled: false
  # -- Path for startupProbe
  path: /health
  # -- Port for startupProbe
  port: 80
  # -- Initial delay seconds for startupProbe
  initialDelaySeconds: 300
  # -- Timeout seconds for startupProbe
  timeoutSeconds: 2
  # -- Period seconds for startupProbe
  periodSeconds: 5
  # -- Failure threshold for startupProbe
  failureThreshold: 5
  # -- Success threshold for startupProbe
  successThreshold: 1

resources:
  requests:
    # -- The cpu resources requests for the containers
    cpu: 100m
    # -- The memory resources requests for the containers
    memory: 128Mi
  limits:
    # -- The cpu resources limits for the containers
    cpu: 200m
    # -- The memory resources limits for the containers
    memory: 256Mi
