{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{ with .Values.ingress.labels }}
    {{ toYaml . | nindent 4 }}
    {{ end }}
  {{ with .Values.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{ end }}
spec:
  rules:
    {{ if .Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          {{- if .Values.ingress.extraPaths }}
          {{- toYaml .Values.ingress.extraPaths | nindent 10 }}
          {{- end }}
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.service.port }}
    {{ end }}
    {{- range .Values.ingress.extraHosts }}
    - host: {{ .host }}
      http:
        paths:
        - path: {{ default "/*" .path }}
          pathType: {{ default "ImplementationSpecific" .pathType }}
          backend:
            service:
              name: {{ $.Release.Name }}
              port:
                number: {{ .port }}
    {{- end -}}
  {{ if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      {{ if .Values.ingress.tlsSecretName }}
      secretName: {{ .Values.ingress.tlsSecretName }}
      {{ else }}
      secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
      {{ end }}
      {{- if .Values.ingress.extraTls }}
      {{- include "common.tplvalues.render" (dict "value" .Values.ingress.extraTls "context" $) | nindent 4 }}
      {{- end }}
  {{ end }}
{{ end }}
